version: "3.8"
services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    command: "npm run dev"
    env_file:
      - .env.local
    networks:
      - app-network

networks:
  app-network:
    external: true
