import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "./provider/NextAuth";
import { getServerSession } from "next-auth/next";

import Header from "./components/layout/Header";
import { nextAuthOptions } from "./utils/next-auth-options";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(nextAuthOptions);

  return (
    <html lang="ja">
      <body className={`${inter.className} pt-10`}>
        <NextAuthProvider>
          <Header session={session} />
          <main className=" mt-0"> {children}</main>
        </NextAuthProvider>
      </body>
    </html>
  );
}
