name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONTV2 }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Log Vercel Configuration
        run: vercel env ls --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: |
          echo "Starting build process..."
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          echo "Build process completed."
      - name: Deploy Project Artifacts to Vercel
        run: |
          echo "Starting deployment process..."
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
          echo "Deployment process completed."
