name: Deploy Next.js App to Vercel
on:
  push:
    branches:
      - main # デプロイするブランチ

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Vercel Deploy
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }} # GitHubシークレットからVercelトークンを取得
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # VercelのOrganization ID
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # VercelのProject ID
        args: --confirm # デプロイ確認をスキップ
